root = "."
tmp_dir = "tmp"

args_bin = ["server"]
bin = "./tmp/main"
delay = 0
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_file = []
kill_delay = "0s"
poll_interval = 0
rerun = false
rerun_delay = 500
send_interrupt = false
[color]
app = ""
main = "magenta"
watcher = "cyan"

[log]
main_only = false
time = false

clean_on_exit = false
[screen]
clear_on_rebuild = false
