root = "."
tmp_dir = "tmp"

args_bin = ["server"]
bin = "./tmp/main"
delay = 0
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
kill_delay = "0s"
poll_interval = 0
rerun_delay = 500
[color]
app = ""
main = "magenta"
watcher = "cyan"

[log]

clear_on_rebuild = false